### ISSUE TITLE
Cannot bind argument to parameter 'LiteralPath' because it is null.

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#103]
The 'home' environment variable do not exist in Windows 10 ?
Tested on MS Azure :
_Microsoft Windows [Version 10.0.10586]_ 
_Microsoft Windows [Version 10.0.10240]_

![bugplasterliteralpath](https://cloud.githubusercontent.com/assets/4894452/18563329/8f4a2f20-7b87-11e6-87cb-2ad6293d1d78.png)
This declaration resolve the problem :
```Powershell
$env:home='C:\Users\Laurent'
```

**Comment by rkeithhill** [comment]
That's a dumb mistake on my part.  It should be just `$Home`.  I'll fix that tonight.

**Comment by LaurentDardenne** [comment]
This line is not affected ?
```powershell
 $gitConfigPath = Join-Path $env:Home '.gitconfig'
```

**Comment by rkeithhill** [comment]
Yes it is.  Late night fix for the last one - missed this one. It is fixed now.  Thanks!
