### ISSUE TITLE
Implement Get-PlasterTemplate

### ISSUE THREAD

**Issue by daviwil** [PowerShell/Plaster#106]
Opening this first for discussion and then to start doing the work :)  Please take a look and give feedback on anything here (naming, paramset design, object design, etc).

Right now we only have the `Invoke-Plaster` and `Test-PlasterManifest` cmdlets but it makes sense to also have a `Get-PlasterTemplate` cmdlet which can gather information about a single template, available templates in a folder path, or templates included with PowerShell modules the user has installed on their machine.  The goal here would be to provide some way for the user to choose which template they'd like to use in a call to `Invoke-Plaster`, either on the command line or in the user interface of an editor like Visual Studio Code.
## Cmdlet Design

I am imagining three paramsets for this cmdlet:
### Get-PlasterTemplate

This paramset will return an array containing the templates that are included with the Plaster module.
### Get-PlasterTemplate -IncludeModules [-Whitelist <string[]>]

This paramset will search the user/machine's installed modules to find any that contain Plaster templates.  Any templates found will be included in the results along with the built-in templates.  If an array of strings is passed to the `-Whitelist` parameter, only templates from any module named in that array will have its templates returned.
### Get-PlasterTemplate -TemplatePath <string> [-Recurse]

This paramset will provide details about the Plaster template(s) at the given path.  If the path points directly to a `plasterManifest.xml` file or a folder containing that file, the information for that module will be returned.  If the path does not contain a `plasterManifest.xml` file then an error will be reported.

If the `-Recurse` parameter is added, the cmdlet will recursively search the given path to locate any folder that contains a `plasterManifest.xml` and return an array containing any templates that were found.

**NOTE:** The `Test-PlasterManifest` cmdlet basically provides this functionality already but it returns the template metadata as a XML object rather than our own domain object.  We could either leave `Test-PlasterManifest` as it is and then wrap it with `Get-PlasterTemplate` or even change the behavior of `Test-PlasterManifest` to return a domain object instead.  Generally it seems to make sense to have a `Get-PlasterTemplate` cmdlet that can be pointed at as specific path, though.  Thoughts?
## Template Metadata Object

The paramsets of this cmdlet will return objects which contain metadata for the template(s) found.  As mentioned before, `Test-PlasterManifest` currently returns this information as an XML object.  I'd like to create a type based on `PSCustomObject` (not classes since I'd prefer to also support PSv3 and PSv4) which contains the information form the manifest XML in its own type.  This type will be expected by the `Invoke-Plaster` cmdlet.
## Usage

The user (or editor integration) will call the form of `Get-PlasterTemplate` which gives them the list of templates (or specific template details) that they are looking for.  Once the user has a template metadata object, they can pass it into a new paramset of `Invoke-Plaster` which contains the `-Template <PlasterTemplate>` parameter.
## New default `Invoke-Plaster` behavior?

This may also allow us to provide a default paramset for `Invoke-Plaster` which can prompt the user about which template they'd like to use based on the ones they have installed on their machine.  Yeoman has this capability; it gives you a list of templates you can choose from if you don't specify one when you invoke the command.
## Template Module Resolution

I won't go into details about how we'll resolve template modules yet because I'm working on a different proposal to address this more generally for all PowerShell modules.  I'll post a link to that proposal once it's ready :)

**Comment by LaurentDardenne** [comment]
Hi David,
_This paramset will provide details about the Plaster template(s) at the given path_
May be Find-PlasterTemplate and Get-PlasterTemplate with : Find-PlasterTemplate -Path -Gallery (PSGallery/MyGet/UNC_Share...)

_I'd like to create a type based on PSCustomObject (not classes since I'd prefer to also support PSv3 and PSv4) which contains the information form the manifest XML in its own type_
May be this is inappropriate, Plaster provide a XSD, it is possible to create a C# class via Xsd.exe and manipulate one instance. PS v3,v4 and v5 use the same dotnet framework (4.0)
 ````Powershell
$plaster|fl
# metadata      : PlasterSchema.plasterManifestMetadata
# parameters    : {ModuleName, ModuleDesc, Version, FullName, Email, Options, Editor, License}
# content       : {PlasterSchema.plasterManifestMessage, , PlasterSchema.plasterManifestFile,....}
# schemaVersion : 0.3

$plaster.parameters|fl
# choice         :
# name           : ModuleName
# type           : text
# prompt         : Enter the name of the module
# default        :
# store          : text
# storeSpecified : False
$plaster.content|fl
# condition :
# nonewline : False
# Value     :
#             Scaffold a PowerShell Module with the files required to run Pester tests, build with PSake and publish to
#             the PSGallery.
# 
# 
# destination   : ${PLASTER_PARAM_ModuleName}.psd1
# author        : $PLASTER_PARAM_FullName
# companyName   :
# description   : $PLASTER_PARAM_ModuleDesc
# moduleVersion : $PLASTER_PARAM_Version
# rootModule    : ${PLASTER_PARAM_ModuleName}.psm1
# condition     :
# encoding      : UTF8NoBOM   #!!! Changed by XSD.exe
# 
# source      : Module.psm1
# destination : ${PLASTER_PARAM_ModuleName}.psm1
# condition   :

$plaster.content[1].GetType().fullname
#PlasterSchema.plasterManifestNewModuleManifest

$Asm=Get-Assemblies|? location -match 'PlasterSchema'
$Asm.ExportedTypes.Fullname
# PlasterSchema.choice
# PlasterSchema.parameter
# PlasterSchema.ParameterType
# PlasterSchema.StoreFormatType
# PlasterSchema.original
# PlasterSchema.substitute
# PlasterSchema.plasterManifest
# PlasterSchema.plasterManifestMetadata
# PlasterSchema.plasterManifestFile
# PlasterSchema.plasterManifestMessage
# PlasterSchema.plasterManifestModify
# PlasterSchema.plasterManifestModifyReplace
# PlasterSchema.encoding
# PlasterSchema.plasterManifestNewModuleManifest
# PlasterSchema.plasterManifestTemplateFile
```

**Comment by daviwil** [comment]
Hey Laurent, thanks for the feedback!

> May be Find-PlasterTemplate and Get-PlasterTemplate

Hmm, I hadn't thought about `Find-PlasterTemplate`, that'd be really nice for finding available templates on the PowerShell Gallery.  I agree, it'd be nice if you could specify which Gallery repository you wanted to use for that.

For `Get-PlasterTemplate`, I think I'd only pull templates that are already installed on the local machine.

> it is possible to create a C# class via Xsd.exe and manipulate one instance

It's certainly possible but the object I have in mind would only have a subset of what is available in the manifest.  It's a good idea though, I'll keep that in mind.

**Comment by rkeithhill** [comment]
> The Test-PlasterManifest cmdlet basically provides this functionality already but it returns the template metadata as a XML object rather than our own domain object.

I went back and forth on this a bit and settled on returning the XML document instead of True/False to eliminate having to read the XML document multiple times.  This command "could" return a domain object like `PlasterTemplateInfo` but at this point, that would be a big change.  First, we'd have to create this domain object and second, all of the script in Invoke-Plaster parties on the XML directly.  

How Inovke-Plaster works internally is an implementation detail that we could certainly change at any point.  However what `Test-PlasterManifest` returns probably shouldn't change over time.  Or maybe we add a new parameterset to have the command return a domain object object like PlasterTemplateInfo instead of XML if a new parameter is specified.

If you'd really like to get the domain object in there for v1, I could modify Invoke-Plaster to use Test-PlasterManifest just for validation and then load the XML document separately.  I'm not sure I'll have time to convert Test-PlasterManifest though in the next couple of weeks. I really want to focus on getting the templates up-to-snuff.

**Comment by rkeithhill** [comment]
> This paramset will return an array containing the templates that are included with the Plaster module.

The manifest file includes a comma separated tags metadata element e.g.:
```xml
<tags>Module, ModuleManifest, Build, Publish</tags>
```
I would hope that a `Get-PlasterTemplate` command would have a `-Tag` parameter where I could specify one or more tags to match on.

The manifest also has these elements that might be useful for displaying:
```xml
<title>New Module Project</title>
<!-- For display by UI's in hover help -->
<description>Plaster template for creating the files for a PowerShell module.</description>
<version>0.2.0</version>
```

**Comment by daviwil** [comment]
Yep, the more I looked at `Test-PlasterManifest`, I felt that it should continue to return the XML document.  In my current prototype, `Get-PlasterTemplate` uses that XML object to return a simple domain object.

I definitely agree that makes sense to not parse the XML again when `Invoke-Plaster` is called.  Maybe on the domain object we can have a `Manifest` property which contains the XML document?  The idea for having a domain object is to just simplify the presentation of the template details for the purpose of listing out modules, etc.

Yeah, tag-based searching with the Get-PlasterTemplate cmdlet would also be helpful, I'll add that!

Right now I'm thinking that domain object could contain:

- Title
- Description
- Version
- Tags
- Manifest

Any thing else?

**Comment by rkeithhill** [comment]
> Maybe on the domain object we can have a Manifest property which contains the XML document?

I was thinking the same thing but didn't want to say it.  Feels a bit like a leaky abstraction but it would probably be OK in this case.  If we ever switched to another file format, that property could remain and be empty or null.

> Any thing else?

You might not want to display it but the `id` field will contain a unique id for each template.  Where this is of use is when you have different versions of the same template (where "same" is determined by the id field).  In this case, we would probably only want to show the latest version of multiple templates that have the same id.

I haven't spent as much time thinking about this aspect of Plaster as I probably should have but there is this issue of identifying templates.  At the moment id works as a good way to uniquely identify templates (like the guid in a PowerShell module).  Title and description were meant for UI purposes only (no need to disallow invalid path chars).  

What we are perhaps lacking now is a `name`.   I was originally thinking we would have one template per pkg where the pkg name *is* the name.  But now we are talking about putting multiple templates in a PowerShell module.  So what do we use for a template name.  The main place I'm using this now is for the default value store ($home/appdata/local/plaster):
```powershell
$templateId = $manifest.plasterManifest.metadata.id
$templateVersion = $manifest.plasterManifest.metadata.version
$templateBaseName = [System.IO.Path]::GetFileNameWithoutExtension($TemplatePath)
$storeFilename = "$templateBaseName-$templateVersion-$templateId"
$defaultValueStorePath = Join-Path $ParameterDefaultValueStoreRootPath $storeFilename
```
The `$templateBaseName` is the directory name and I use that for a template name.  This gives a default value store filename of:
```
NewModuleTemplate-38bd80d9-0.2.0-3a47-4916-9220-bed383d90876.clixml
```
Not sure that's the best approach. It's certainly not obvious the folder is being used for this purpose.  And template "name" is more natural for something like finding templates.  Maybe I want to look for a template named "NewDscResource" in which I case I may find multiple hits (that's OK), if I can see the description.  And I guess I'd like to see `author` information which is currently not in the schema.  Hmm, that seems like a gap.  I propose adding an `<author>` element to the metadata.  Should it be required?  Perhaps we should add a `<name>` element as well to provide a "human friendly" term to search for a template on?

**Comment by rkeithhill** [comment]
OK I'm adding `<author></author>` to the manifest metadata.  Even though the contain PowerShell module has an author field, I can see someone packages templates from multiple authors into a single PowerShell module.

**Comment by daviwil** [comment]
Agreed on the leaky abstraction, I had started to ask whether there's a way we could hide the manifest property in the domain model object but then decided that maybe it's not worth it.  I think just having it excluded from the formatting output would be enough to de-emphasize it while still allowing it to be there in case a user wanted to check the manifest contents.

Yeah, Author is a great field to have.  Since you mentioned inheriting fields from the module which shipped the template, that actually makes sense as a way to build a unique template name.  The manifest file could have a `name` field which defines the individual template's name, but when the template is resolved from within a module we could use the module name as a namespace, i.e. `Plaster.NewModule` or `PSScriptAnalyzer.NewRule`.  For any template that's not contained in a module, the author could do their own namespacing in the `name` field if it mattered.

**Comment by daviwil** [comment]
Random thought, I wonder if there should also be an optional parameter to specify the desired language for templates in case a template has a localized version?  Right now I'm just scanning folders for `plasterManifest.xml` but it might make sense to look for specific language variants of the template as well.

**Comment by rkeithhill** [comment]
> The manifest file could have a name ...

Agreed.  I'm going to add name to the schema as required and to the New-PlasterManifest command.  Title will be optional and if the title is missing (or empty) we will drop back to the name field for a short, display name to use in a user interface (like in VSCode).

> I wonder if there should also be an optional parameter to specify the desired language 

The current implementation has the plasterManifest.xml file act at the culture fallback.  If there are no culture-specific manifest file names that match up to $PSCulture, then plasterManifest.xml is used.  However, that fallback file doesn't have to be en-US.  Unfortunately, there is no metadata for the culture of a plasterManifest.xml file.  So we are left guessing about the culture of the default manifest file.

We could add lang/culture as a metadata element. But if we do that, it might be weird having that info in metadata and in the filename.  I guess we could use subdirs like `fr-FR` and `de` and then the manifest filename would always be `plasterManifest.xml` with `fr-FR\plasterManifest.xml` and `de\plasterManifest.xml`.

**Comment by daviwil** [comment]
Maybe Title should be mandatory?  I think the Name value itself may indicate what the template does but the Title gives a better experience.  Also, only the Title can be localized.

Ahhh, if Invoke-Plaster figures out the filename of the manifest variant for the current culture, that's good enough for me!  Probably not worth it to have lang/culture as a metadata element, the file naming convention is good enough for now.

**Comment by rkeithhill** [comment]
OK name is required in the manifest and title is now required as well.  Just submitted a PR for it.

**Comment by daviwil** [comment]
Awesome, thanks!

I'll be getting back to the `Get-PlasterTemplate` work soon, got sidetracked on some PSES work that just won't finish...

**Comment by gerane** [comment]
I was thinking about Find-PlasterTemplate, and though it might be worth looking into creating a custom OneGet provider specifically for Plaster templates. 

It could be installed with the module and the Find-PlasterTenplate could be a wrapper to search both the custom provider and the PowerShell gallery for module tagged plaster template.

The reason I was thinking about this, is I can see Plaster gaining adoption outside of PowerShell, so it might be nice to have a provider dedicated to templates. Then we could embed a template for creating and publishing plaster templates to the plaster template provider.
