### ISSUE TITLE
Add requireModule directive

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/Plaster#112]
For the first version of Plaster this directive will only notify the user that a required module is missing.  In a future version (if PackageManagement and PowerShellGet are installed) it could offer to install the modules for the user.

Here is what the directive looks like in the manifest:

```xml
<requireModule name="Pester" condition='$PLASTER_PARAM_Options -contains "Pester"'
    minimumVersion="3.4.0"
    message="Without Pester, you will not be able to run the provided Pester test to validate your module manifest file.`nWithout version 3.4.0, Visual Studio Code will not be able to display Pester warnings and errors in the Problems panel."/>

<requireModule name="psake" condition='$PLASTER_PARAM_Options -contains "PSake"'
    message="Without psake, you will not be able to run the provided build script to build and/or publish your module."/>
```
In addition to `minimumVersion` there is also a `maximumVersion` attribute than can be used with `minimumVersion`.  There is also a `requiredVersion` attribute that is mutually exclusive with the first two.

This is what the UI looks like for `<requireModule>`:

![image](https://cloud.githubusercontent.com/assets/5177512/18612935/ff5033ae-7d27-11e6-9357-ca88829993a9.png)

Ignore the fact that the message says the ModuleVersion 3.5.0.  I set it to that version temporarily to trigger the missing module message.  The version of Pester that supports VSCode better is 3.4.0.

**Comment by rkeithhill** [comment]
Reopening just for a few days so folks can see this info on the feature.

**Comment by LaurentDardenne** [comment]
IMHO the case 'missing' should be an error (not an exception), the caller do not know what it happens.
I cannot trigger a rollback if necessary.

**Comment by LaurentDardenne** [comment]
_Are you saying that invoke should stop on a missing module?_ 
Not necessarily stop, but at least warn the user. 
To Stop, I can use "-EA Stop".

_Also what needs to be 'rolled back'?_
Remove the scaffold (files).

**Required** module should be tested first,

May be rename the element to 'InstallModule" and add a optionnal attribut _Required_ ?

**Comment by rkeithhill** [comment]
The intent of the directive is to let the user know that a module is missing for some part of the functionality.  That functionality may or may not be key to basic usage of the resulting files.  The idea was to let the user know that they need to install the required module for that functionality.  I don't think it is worth rolling anything back - which Plaster does not support at this time.  

Eventually, I would like for `<requireModule>` to prompt the user to install the missing module but @daviwil and I thought that functionality could be added later.  We are shooting for a mid-October original release which is aggressive given what we have left to do.  

Perhaps, I should change the `Missing` color from red to yellow as this is more of a warning than an error.

**Comment by davegreen** [comment]
I think that a notification like the one shown in the first post would be fine for an initial release, as installing the prerequisite modules for a particular template is probably not as important as getting the templates and scaffolding spot on for 1.0 given the proposed timescale. Making requiremodule respect the error action preference to is probably worth doing though.

**Comment by LaurentDardenne** [comment]
_I don't think it is worth rolling anything back - which Plaster does not support at this time._ 
I do not need this feature inside Plaster, i would just known "there are one error".

_That functionality may or may not be key to basic usage of the resulting files._
I understand your intention, but for me the word 'require' is a constraint (it is obligatory).
 
_Eventually, I would like for <requireModule> to prompt the user to install the missing module_
It is not necessary. by example if i use Appveyor, this is not possible.

**Comment by rkeithhill** [comment]
RE Appveyor, the idea is that if this directive eventually can install the module then the Force parameter would not prompt. It would just install the module. Also scaffolders like this tool are usually for delivering a starting set of files instead of a "completed" set of files.

**Comment by LaurentDardenne** [comment]
_Also scaffolders like this tool are usually for delivering a starting set of files instead of a "completed" set of files._
I agree that I change a bit of use of Plaster. 

I try to create a [template for a new project](https://github.com/LaurentDardenne/TestProject) (new module + build(10 tasks) and I need 3-4 modules and 5-6 scripts as dependencies.
Plaster can not download zip files, for that, I created a [feed](https://www.myget.org/gallery/ottomatt) on myget.
On my computer all required modules are installed, if I create a new project on a VM, the required modules MUST be installed.

The question I most often ask myself is "must i use Plaster  or a setup script or a PSake task" :-)
May be I use the wrong tool...

**Comment by daviwil** [comment]
I think a psake task combined with Plaster sounds like a good option for that.  Your psake task can do the necessary module/zip installation and then invoke Plaster to scaffold your project.
