### ISSUE TITLE
Use \tests not \test

### ISSUE THREAD

**Issue by lholman** [PowerShell/Plaster#129]
First off, fantastic work, I've just created my first module based on the default Plaster template.
Is it possible to specify \tests as the Pester test folder instead of \test without editing the generated psake script?
The reason I ask is I have been recently pushing to adopt many of the guidelines for high quality DSC modules in the PowerShell DscResources repo @ https://github.com/PowerShell/DscResources/blob/master/HighQualityModuleGuidelines.md these use the plural \Tests for the root tests folder name and I'd like consistency.
I realise this would be a breaking change, but seeing as you're approaching first release maybe now would be a good time?
Happy to submit a PR

**Comment by rkeithhill** [comment]
I was looking at some of the newer PowerShell projects on GitHub like PowerShell, platyPS which inspired me to use `test`.  That said, I'm not  necessary opposed to `tests`.  We discussed module structure a little here https://github.com/PowerShell/Plaster/issues/2  And the current example NewModuleTemplate is about to updated to something we can call a "production quality" New Module template.

**Comment by daviwil** [comment]
`test` is more commonly used across language communities, so I'm in favor of it from that perspective.  However, if it's going to annoy people too much, we can certainly go with `tests`.  Thought about doing a Twitter poll but those tend to get pretty biased responses :)

**Comment by rkeithhill** [comment]
We are going with `test`.  @daviwil Any chance you could influence the folks on the DscResources project to consider changing their guidance?  If not, we could have a separate template for a DscResource module that uses `tests`.

**Comment by kilasuit** [comment]
@rkeithhill & @daviwil - I see that this should be \Tests and not \Test like @lholman has suggested - mainly because this is already more common across most PowerShell based repositories on Github

I can see the point that @daviwil made re other languages but this to me just makes more sense to keep with what the rest of the community has already got in the habit of using.
