### ISSUE TITLE
Add a way to add files without specifying them in Manifest.

### ISSUE THREAD

**Issue by gerane** [PowerShell/Plaster#13]
If I am dealing with a project that has a very large number of files that are static and don't need to be edited or controlled by a condition, it makes using Plaster very cumbersome. This is especially true if you have a template directory that changes often or has new files added often.

I think a better way to address this might be to have a directory inside of the Root of the zip that Represents your directory structure and any static files that are always going into your project. Then have any Template and Conditional files in another location that are added based on the criteria.

Another option would be to automatically add everything in the zip, and then edit the template files and remove any items that don't meet a condition. Instead of adding the ones that meet conditions, we would be doing the opposite. I like this sort of option best.

Another would be to at least allow adding folders with wildcards for all items under that folder. Maybe something like the example below.

``` xml
<file source='Root\Dir1\*'
        destination='Root\Dir1\*'/>
<file source='Root\Dir2\*'
        destination='Root\Dir2\*'/>
```

**Comment by daviwil** [comment]
I think this would be pretty helpful but I haven't thought through the impact it might have yet.  What do you think Keith?

**Comment by gerane** [comment]
You could add an ignore file for anything used for processing or with Plaster. Then for the template files that get edited for variables, just go to the path of the file and edit it instead of copy it. Then for the files with conditions, remove based on condition instead of add based on condition. Example:

Options: A, B, C
Current: User selects B, Plaster adds B.
Proposed: User Selects B, Plaster Removed A and C.

**Comment by gerane** [comment]
I am just thinking that if Plaster is meant to support any sort of project, it's current implementation is not really feasible for something with say, 50, 100, 1000 or however many individual files. You would have to manually add each file into the manifest to be copied over.

**Comment by rkeithhill** [comment]
RE root folder - I was thinking that we might follow NuGet's lead on this and put content under a `content` folder.   This also helps make it obvious that plasterManifest.xml is special and not a content file.

Likewise, I think we could support a wildcard syntax.  NuGet uses:
```xml
  <file src="tools\**" />
```
I can see how that would be useful.

**Comment by rkeithhill** [comment]
@gerane Can you give me a user scenario for scaffolding that would require 1000 files?  I want to make sure I understand those scenarios.

**Comment by gerane** [comment]
Something like that sounds good. 

I don't really have an example atm of say 1000. However, my very first I decided to try out was for PSAppDeployToolkit. I am constantly adding more files to this since I am sort of building a module of helper functions for it. I think currently its around 35-40 files. The manifest in this link doesn't have all of them because I decided to stop and come make an issue first. You can at least start to get an idea of how cumbersome it could get to create or maintain a template that has a large number of files or changes regularly.

https://gist.github.com/gerane/38ac0bcb14533a17eeaf892ee0612046

If I had to think of something that might use 1000 files, it might be more of a project that might include other helper modules inside of it. These Helper Modules might be static and contain hundreds of files, but you would still need to add every single file in the Help Modules by hand. 

We also have to think about what potential projects this might be used for. Modules, DSC Resources, Pester and things like that might be your first thoughts, but a tool like this can be used for so much more than just that. Since PowerShell is such a Operations type language, I think we should try to look at Plaster in the same way we should look at Pester. There is the standard use case like Unit Tests, but then there are those other awesome use cases that people don't even realize like Operational Validation tests.

**Comment by gerane** [comment]
If the nuget wildcard were added though, this would clear up a large amount of the issue.

**Comment by rkeithhill** [comment]
Thanks.  Given your example I can see how having a wildcard would be very handy.
