### ISSUE TITLE
PowerShell Output Error in VS Code

### ISSUE THREAD

**Issue by gerane** [PowerShell/Plaster#14]
If I open the InvokePester.ps1 file in VS Code I get an error in the PowerShell Output. Anytime I swap between another file and InvokePester.ps1 this error occurs.

```
Suppression Message Attribute error at line 16 in InvokePlaster.ps1 : Cannot find any Targets ModifyContent that match the Scope Function to apply the SuppressMessageAttribute.
```

**Comment by rkeithhill** [comment]
Thanks.  I changed the name of a function and didn't update the SupressMessage attribute.  I fix that tonight.
