### ISSUE TITLE
New-PlasterManifest produces a manifest that fails Test-PlasterManifest

### ISSUE THREAD

**Issue by cdhunt** [PowerShell/Plaster#153]
As of the code I pulled down on 10/10.

```VERBOSE: Plaster manifest schema error: The 'schemaVersion' attribute is invalid - The value '' is invalid according to
 its datatype 'http://www.microsoft.com/schemas/PowerShell/Plaster/v1:SchemaVersionType' - The Pattern constraint
failed.```

**Comment by cdhunt** [comment]
Okay, nm. Too many copies of Plaster source I guess.

**Comment by rkeithhill** [comment]
That's OK. In the process of testing this I found another bug.

**Comment by cdhunt** [comment]
For some reason, everything tied to `$LatestSupportedSchemaVersion` was going crazy. Then I went to debug it and it was working.
