### ISSUE TITLE
Multichoice PromptForChoice does not work as intended in ISE or VS Code.

### ISSUE THREAD

**Issue by gerane** [PowerShell/Plaster#16]
I have posted some examples here: https://gist.github.com/gerane/b40a4755fc249ed420c49ae8fef947f9

When specifying [Int[]] for Default value in order to take Multiple selections, it breaks the GUI portion of the Prompts and forces it to console. 

In ISE you can still use it, but it might be confusing to users to have some prompts in a GUI and some in console.

The bigger issue is in an Editor like VSCode. If the user doesn't have their output open, they won't even see their options. They are in the console, but being prompted by a blank prompt that only has a ":". I think this will really confuse most users. 

Here is a gif showing what it looks like.

![](https://raw.githubusercontent.com/gerane/PowerShell/master/vscodeprompt.gif)

**Comment by daviwil** [comment]
I'll have to look into this, maybe there's some way for PSES to know how to deal with this appropriately.  Still won't be possible to allow multiple selection with VS Code's selection box, so I'm not sure what the right UI would be in this case...

**Comment by rkeithhill** [comment]
Yo does it somehow:

![yo](https://cloud.githubusercontent.com/assets/5177512/15492051/41922b3c-2134-11e6-9131-cfaa3163c392.png)

From the Usage animated gif on the [extension's marketplace page](https://marketplace.visualstudio.com/items?itemName=samverschueren.yo).

**Comment by daviwil** [comment]
Heh, interesting hack.  They're basically showing the same list multiple times with special characters to show the checked state.  Pretty clever.  I think we can replicate that.

**Comment by gerane** [comment]
I was wondering why PromptForChoice wasn't doing this itself. Odd the way it works.

**Comment by gerane** [comment]
Could you potentially do this for all prompts to get better formatting and to handle timeouts and errors more appropriately?

**Comment by daviwil** [comment]
Could you give an example of what you mean?  Unfortunately I don't have a lot of control over VS Code's UI

**Comment by gerane** [comment]
I guess it isn't that bad if you remove the multichoice options. The one quirk is the '-' that shows up for choice options.

**Comment by rkeithhill** [comment]
Also, when running this from the debugger, we still have this issue where "blank" input is not passed back to PowerShell.  This makes it impossible AFAICT to end a multichoice input from the debug console (without aborting the script).

**Comment by gerane** [comment]
Best way is likely to reload the window.

**Comment by rkeithhill** [comment]
@gerane This is not really a Plaster issue. Could you submit this issue to the https://github.com/powerShell/vscode-powershell project?
