### ISSUE TITLE
Where do we store Plaster default value store on Linux/macOS?

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/Plaster#162]
On Windows, we use the path `$env:LOCALAPPDATA\Plaster` which I don't think will work on PS Core.  Any suggestions on where this sort of setting file should go?

**Comment by davegreen** [comment]
We'd have to do edition/platform detection before saving data, but I think we'd be best served following common placement for files depending on the platform, for Linux/macOS, probably something like `$env:USERPROFILE\.plaster` might fit.

**Comment by PowerSchill** [comment]
What about $Home\.plaster? You could use that on any platform.

**Comment by rkeithhill** [comment]
`~/.plaster` is what I've tentatively been using  on a branch I created for PSCore port issues.  But know I'm thinking it should go under `~/.local/share/Plaster` ($XDG_DATA_HOME ) based on this https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html.  

This file BTW isn't really a user-configured file so I don't think it belongs in `~/.config`.

**Comment by rkeithhill** [comment]
This is what I'm currently using.  Anybody with a Mac feel free to provide a better location than `$Home/.plaster`.
```powershell
if ($IsWindows) {
    $ParameterDefaultValueStoreRootPath = "$env:LOCALAPPDATA\Plaster"
}
elseif ($IsLinux) {
    # https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
    $ParameterDefaultValueStoreRootPath = if ($XDG_DATA_HOME) { "$XDG_DATA_HOME/plaster"  } else { "$Home/.local/share/plaster" }
}
else {
    $ParameterDefaultValueStoreRootPath = "$Home/.plaster"
}
```

**Comment by rkeithhill** [comment]
I believe we have addressed the location on all supported platforms.
