### ISSUE TITLE
Question about 'New-PlasterManifest' function

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#165]
The New-PlasterManifest do not manage the schema version (xsd).
When I want to create an Plaster Manifest for an precedent schema I must use the appropriate version of the plaster module ?

**Comment by rkeithhill** [comment]
I'm not sure I follow your question entirely.  But if you want to target an earlier version of Plaster (and earlier schema) then I suggest you use an earlier version of Plaster.  That way you can test against that earlier version.  Right now, `New-PlasterManifest` should always target the latest version of the schema for that version of Plaster.

**Comment by LaurentDardenne** [comment]
_"But if you want to target an earlier version of Plaster (and earlier schema) then I suggest you use an earlier version of Plaster."
Ok, 
The New-PlasterManifest  documentation don't talk about this point.

**Comment by rkeithhill** [comment]
Sorry, docs are still in need of improving ... a lot.
