### ISSUE TITLE
Add the file 'launch.json' for VScode

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#168]
Adding the file 'launch.json' into [VSCode directory template](https://github.com/PowerShell/Plaster/tree/master/src/Templates/NewModule/editor/VSCode) would be appreciated.

**Comment by rkeithhill** [comment]
I'm not sure about providing this file. My worry is it getting out of sync with changes that VSCode makes to their file format.  Right now it isn't too bad to get this file created.  You press F5 and then select PowerShell from the drop down.

**Comment by daviwil** [comment]
Yeah, we should let the VS Code extension handle this.  Our use of the launch.json file is gradually changing over time so it doesn't make as much sense to create this file from the initial template.  Thanks for the suggestion!
