### ISSUE TITLE
Add support for reporting on code coverage in Pester tests

### ISSUE THREAD

**Issue by PowerSchill** [PowerShell/Plaster#177]
It would be a helpful addition to be able to view the results from the code coverage functionality of Pester. It would allow for making sure Pester tests account for all of a modules functionality. 

Bonus points would be if you could also in fact have a Pester test that would calculate a codecoverage and test on that. For example making sure you account for 100% of your code in tests.

**Comment by rkeithhill** [comment]
We can certainly add an option to enable code coverage in the build script.  I"ll look into that tonight. 

BTW given my experience with code coverage in C# code, it is hard to get 100% coverage and at some coverage level you hit the point of diminishing returns.

**Comment by davegreen** [comment]
Some initial Pester code coverage options exist as of #181.

@PowerSchill It's not a Pester test to calculate coverage, but seems to provide some reasonable starting options in the same theme as other Plaster build options for both reporting on code coverage or failing on insufficient coverage, depending on your needs.
