### ISSUE TITLE
GenerateModuleManifest checks for $Filenode.condition but is note a FileNode

### ISSUE THREAD

**Issue by gerane** [PowerShell/Plaster#18]
This function checks for a condition using `$FileNode.condition` but I believe that is going to always return false since it is a `newModuleManifest` instead of a `FileNode`

```powershell
$condition  = $FileNode.condition
if ($condition) {
    if (!(EvaluateCondition $condition)) {
        Write-Verbose "Skipping module manifest generation for '$dstPath', condition evaluated to false."
        return
    }
}
```

I would think you would need the following, but I wasn't sure if I was missing something.

```powershell
$condition = ExpandString $NewModuleManifestNode.condition
```

Then you could add a Manifest condition like this:

```xml
<newModuleManifest destination='${PLASTER_PARAM_ModuleName}.psd1'
    moduleVersion='$PLASTER_PARAM_Version'
    rootModule='${PLASTER_PARAM_ModuleName}.psm1'
    author='$PLASTER_PARAM_FullName'
    condition="$PLASTER_PARAM_Manifest -eq 'Yes'"/>
```

```xml
<parameter name='Manifest' type='choice' default='0' prompt='Create a Module Manifest?'>
    <choice label='&amp;Yes'
            help="Adds Manifest."
            value="Yes"/>
    <choice label='&amp;No'
            help="Skips Manifest."
            value="No"/>
</parameter>
```

Currently, if you set a condition like the example above, it ignores the condition and makes the manifest regardless.

**Comment by rkeithhill** [comment]
Thanks for spotting this. I'll fix it later tonight.

**Comment by gerane** [comment]
I thought about doing a pull request, but wanted to make sure I was on the same page first.

**Comment by rkeithhill** [comment]
Right now I'm not using ExpandString on the condition attribute value.  That would reject the value if it's anything other than a constant string for variable string expression.  In order to make conditions work for now, we pass the attribute value directly to EvaluateCondition. 

Go ahead and submit a PR but do me a favor and test this code more than I apparently did.  :-)
