### ISSUE TITLE
Discussion: Add a default template for a Basic\Beginner Module Template.

### ISSUE THREAD

**Issue by gerane** [PowerShell/Plaster#194]
I wanted to get more discussion going on this. This is a quick example of what I was speaking to you about at the MVP Summit @rkeithhill 

I have spoken with a large number of people in the PowerShell community that have loved Warren Frame's example of a module structure that he has shared here: [https://ramblingcookiemonster.github.io/Building-A-PowerShell-Module/](url)

I found that structure when I was trying to figure out the best way to build a module and it immediately made sense to me. I think it is a great structure for those learning. 

The basic structure is the following:
Module\
- Public\                                         (Public function scripts that get exported)
- Private\                                        (Private function scripts that do not get exported)
- en-US\about_Module.help.txt
- Module.psm1    
- Module.psd1

The psm1 might look something like the one in the link above. The example below could be augmented by comments explaining how the Public and Private folders work.

```powershell
$Public = @(Get-ChildItem -Path $PSScriptRoot\Public\*.ps1 -ErrorAction SilentlyContinue)
$Private = @(Get-ChildItem -Path $PSScriptRoot\Private\*.ps1 -ErrorAction SilentlyContinue)

# Dot Source Functions
Foreach ($import in @($Public + $Private))
{
	Try
	{
		. $import.fullname
	}
	Catch
	{
		Write-Error -Message "Failed to import function $($import.fullname): $_"
	}
}

Export-ModuleMember -Function $Public.Basename
```

Another option might be to just have a psd1 and psm1 and not even have the Public and Private folders. This could also be added as an option to the Manifest. 

A user might feel overwhelmed with all of the options the Current template has to offer. I think having a default pair of a Basic and Advanced might be a good way to make Plaster more inviting to those learning. I think Plaster is a great tool that can be used to help people learn PowerShell, but I want to avoid people thinking it is too complicated and shy away from it. I think a very basic structure with just a few options might be a great way to start.

Some of the options I felt might be ones that might potentially be worth including are the following:
- Description
- ModuleName
- FullName
- License (Default No, but maybe even exclude this one?)

There are other options that could vary as well. 

Here is an example of a basic/beginner template Manifest

```xml
<?xml version="1.0" encoding="utf-8"?>
<plasterManifest
    schemaVersion="0.4" xmlns="http://www.microsoft.com/schemas/PowerShell/Plaster/v1">
    <metadata>
        <name>NewBasicModule</name>
        <id>a9510370-d50b-4d9c-8ec6-2d87893af59e</id>
        <version>0.1.0</version>
        <title>New Basic Module</title>
        <description>Scaffolds the files for a Basic PowerShell Module</description>
        <author>Brandon Padgett</author>
        <tags>Module, ModuleManifest, Beginner, Basic</tags>
    </metadata>

    <parameters>
        <parameter name='ModuleName'
                   type='text'
                   prompt='Enter the name of the module'/>

        <parameter name='ModuleDesc'
                   type='text'
                   prompt='Enter a description of the module (required for publishing to the PowerShell Gallery)'/>

        <parameter name='FullName'
                   type='user-fullname'
                   prompt='Enter your full name'
                   store='text' />

        <parameter name='License'
                   type='choice'
                   prompt='Select a license (see http://choosealicense.com for help choosing):'
                   default='0'
                   store='text'>
            <choice label='&amp;None'
                    help="No license."
                    value="None"/>
            <choice label='&amp;Apache'
                    help="Adds an Apache license file."
                    value="Apache"/>
            <choice label='&amp;MIT'
                    help="Adds an MIT license file."
                    value="MIT"/>
        </parameter>                           
    </parameters>

    <content>
        <message>&#10;&#10;Scaffolding your PowerShell Module...&#10;&#10;&#10;</message>

        <newModuleManifest destination='${PLASTER_PARAM_ModuleName}\${PLASTER_PARAM_ModuleName}.psd1'
                           moduleVersion='$PLASTER_PARAM_Version'
                           rootModule='${PLASTER_PARAM_ModuleName}.psm1'
                           author='$PLASTER_PARAM_FullName'
                           description='$PLASTER_PARAM_ModuleDesc'
                           encoding='UTF8-NoBOM'/>

        <file source='src\Module.psm1'
              destination='${PLASTER_PARAM_ModuleName}\${PLASTER_PARAM_ModuleName}.psm1'/>
        <file source=''
              destination='${PLASTER_PARAM_ModuleName}\Private'/>
        <file source=''
              destination='${PLASTER_PARAM_ModuleName}\Public'/>
        

        <templateFile condition="$PLASTER_PARAM_License -eq 'Apache'"
                      source='license\Apache.txt'
                      destination='LICENSE.txt'
                      encoding="UTF8-NoBOM"/>
        <templateFile condition="$PLASTER_PARAM_License -eq 'MIT'"
                      source='license\MIT.txt'
                      destination='LICENSE.txt' />
        <templateFile source='en-US\about_Module.help.txt'
                      destination='${PLASTER_PARAM_ModuleName}\en-US\about_${PLASTER_PARAM_ModuleName}.help.txt' />                      

        <message>

Your new PowerShell module project '$PLASTER_PARAM_ModuleName' has been created.

        </message>
    </content>
</plasterManifest>
```

I see Plaster as a tool I can use to teach someone how to start writing modules. You can have them install Plaster, and invoke a default template to immediately get started. The build portions are just way too complex for that scenario. Having a good starter template as a default lowers the barrier to entry for beginners. 

I am not quite sure what the naming scheme should be, but it could be something talked about if this is decided to be a worthwhile addition to Plaster.

I have this Template created and played around with it to create a few examples.

**Comment by davegreen** [comment]
This sounds like a really good approach, both as a teaching exercise and to bolster the available help with examples that can just be used straight away to get going. This is especially true since the current module template is (imo) targeted more towards users working with PowerShell on a daily/regular basis.

There should definitely be templates like this to make it easier to both teach (and learn) both PowerShell and specific techniques that can be used to assist in developing modules and I'm definitely in favour of a quick start ready to go template, although I think for some types of examples, this is the value of the planned search/download Plaster template commands, which will greatly simplify getting and using templates.

**Comment by gerane** [comment]
@davegreen I know a lot people who work with PowerShell on a daily basis and still don't use git. I think the included template currently is for much more advanced users that already have a lot of experience with these tools. I would even go as far that it would be over the head of many PowerShell MVPs who have not worked with this sort of pipeline before. It would be overwhelming for most users, which is why I think another option with a less Dev feel to it would be very helpful addition. Then as those users start to learn more and get a hang of things, they can start to branch out and look at the different parts of the more advanced template.

I think an easy, beginner module template makes sense as one of the default options since it lowers the barrier for newer users of powershell to start using Plaster without figuring out how to find new templates. If you are new to the idea of Plaster and have not used Yeoman or the other frameworks, I can see the advanced template being too overwhelming since they are just trying to get an understanding of what Plaster actually is. Trying to the figure out all of the intricacies of the build script and the large number of steps involved in it might push new users away. I have some other templates that I may submit as examples, but wouldn't expect them as default templates. When the support for embedded templates in modules is added I would just add them to the gallery in an existing module or standalone template.

The way I was looking at it, if you really only wanted default support for one module template, it's better to go with the most basic one that the largest number of people can use and get benefit from. Those who can use the more advanced templates, should easily be able to find the more advanced templates or might want to make their own. However, if you are newer to powershell, you might not know how to use the gallery, understand the Gallery categories, or something like that, so an easier default would make sense. However, I dont think that is necessary either and don't see why you couldn't have more than one default template for modules.

**Comment by rkeithhill** [comment]
> I think the included template currently is for much more advanced users that already have a lot of experience with these tools. 

We are going to create a very simple Module template.  

> Trying to the figure out all of the intricacies of the build script and the large number of steps involved in it might push new users away

We have decided *not* to copy any build script into the user's folder.  We haven't decided where we will put the build script.  It could be in Plaster but more likely in another module that depends on psake.  This will allow us to provide updated versions of the build script without breaking anybody because we will maintain older versions of the build script.  

I would also add that we do not expect "average" PowerShell users to trawl through the build script.  I've been using the MSBuild-based build system in Visual Studio since it came out in Feb 2002.  I never think about all the stuff those msbuild targets files do internally. They just work.  It's nice!  Back in the 90's we had to mess around with makefiles a lot and that was a bit of a drag.

**Comment by gerane** [comment]
@rkeithhill I guess I am just so used to these not being a one size fits all. I typically find I have to add custom steps or change steps here or there. Certain integrations might require the user to actually go in and edit certain aspects in order to add something new.

One example for me would be wanting to use ReadtheDocs to host my markdown help files as a webpage, I likely have to change the directory layout of my markdown help slightly, which might also break the build script. 

The build settings file and module sounds very interesting though.  I think there is a ton of potential to have a build module that abstracts a lot of the work away. Especially if it is made extensible. That was one of my favorite parts of PSDeploy. You could pretty easily add new support for other types of deployments, but I always thought it had much more potential than just deployment, and felt things like Pester, ScriptAnalyzer and all of those sorts of tasks could easily be handled as well. Which would give the user a nice DSL to see all of the configuration for the build.

**Comment by daviwil** [comment]
Great feedback!  Like Keith said, we're going to promote the build script to its own module.  Since the complexity will end up being hidden inside of the module, we might be able to do allow people to add new tasks to it over time or make it easy to add new tasks outside of the original script.  The Before/After hooks would make this pretty easy.

For the basic in-box template, I think it might be generally useful to have an option for generating an initial Pester test file.  I also think it might be cool if we could optioanlly generate an appveyor.yml file which will give the user a simple CI integration.  What do you think?

**Comment by ngetchell** [comment]
Having a CI file created automatically would be nice. I use Jenkins, GitLab CI, and Appveyor so I added a prompt to my Plaster template asking which to use. 

My personal belief is the more Plaster does for the module author the more time can be spent on writing the actual module. That being said, you guys made it easy for the community to step in and provide other templates if you choose not to include the appveyor.yml.

**Comment by gerane** [comment]
@ngetchell I've added appveyor and a few other things to my personal one, but I'm still trying to figure out how to properly handle CI/CD with the build script. How are you handling it? 

Since appveyor is triggered at commit or pull request, any changes or tasks that happen during the build script in appveyor are now out of sync with your local and git repository. Say you update and build help, sign scripts, update psd1, update ReleaseNotes/changelog and other things like that, could cause potential problems since that is happening after the commit.

It makes me a little scared to publish via appveyor, what of building your help or updating psd1 randomly failed but didn't trigger any tests, and gets published during the build. Your wouldn't have the problem checked onto your repo so could make debugging a nightmare.

**Comment by ngetchell** [comment]
I see the changes after the commit as things I wouldn't want in a commit anyways. I don't want simple changes in a PSM1 generating large changes in my git history which is what would happen if I signed my work before committing. 

I also merge all of my PS1 files into one big PSM1 but hate developing against one giant file. I'm fine with the PSM1 being generated only through my CI build process. 

You can then make sure your checks run after your build process. Merge the functions into one file, sign the files, generate the help, etc THEN run my pester tests. 

If your build process is deterministic you shouldn't have too much issue debugging. You just run your build and debug the output.

**Comment by daviwil** [comment]
@ngetchell interesting, you're the second person now I've heard who concatenates a bunch of .ps1 files into a .psm1 file.  Is that for performance reasons or deployment simplicity?

**Comment by rkeithhill** [comment]
A very basic PowerShell module template has been created.  And I mean very simple.  I'm going to close this issue.  If you find issues with the new template, submit a new issue.
