### ISSUE TITLE
Provide Plaster template snippets

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/Plaster#199]
I put together some Plaster snippets for the MVP summit.  We should provide those snippets in some manner.  I could put them in a Snippets folder in Plaster but then how do the snippets get picked up automatically by VSCode?

**Comment by daviwil** [comment]
I dunno if they would get picked up by VS Code...  Good question though, need to think of a good way to enable a PowerShell module to contribute editor snippets.
