### ISSUE TITLE
Add a -PassThru parameter to Invoke-Plaster

### ISSUE THREAD

**Issue by daviwil** [PowerShell/Plaster#218]
It'd be helpful if `Invoke-Plaster` had a `-PassThru` parameter which causes the cmdlet to return a PSObject containing the following details:

- Success or failure of scaffolding
- The fully-resolved DestinationPath
- List of files that were created/changed?

This information can be used by PowerShell Editor Services to improve the Plaster integration.

**Comment by rkeithhill** [comment]
I'll look into this today.  First two should be easy.  The last one hopefully shouldn't be too hard.

**Comment by daviwil** [comment]
The last one isn't absolutely necessary, I was just thinking of other things we could add since we're already doing it :)

**Comment by rkeithhill** [comment]
Check out the PR and see how it works for you.
