### ISSUE TITLE
Set up AppVeyor to run Pester tests for pull requests

### ISSUE THREAD

**Issue by daviwil** [PowerShell/Plaster#22]
I need to set up an AppVeyor build for Plaster using the PowerShell organization's account.  Not a lot of work required, just need to take some time to do it.

**Comment by daviwil** [comment]
Just created a new AppVeyor project for Plaster, I'll see if I can get the Pester tests running in there today.

https://ci.appveyor.com/project/PowerShell/plaster

**Comment by rkeithhill** [comment]
Cool.  Are you going to set up script signing?

**Comment by daviwil** [comment]
I'll have to sign the scripts manually before each release. I have to use the Microsoft certs and they don't allow you to automate signing unless you're using an internal build system :/

**Comment by rkeithhill** [comment]
Ah, I was curious about that.  If you can tell me the name of the cert (subject name) we can add that to the build.psake.ps1 script.  Then you can build (or is publish) using VSCode from a machine that has that cert installed and it should sign the scripts.  @davegreen upgraded our psake build script to sign scripts.

**Comment by daviwil** [comment]
There isn't a machine we can access with the certs on it, they have a signing service that we have to submit binaries and scripts to which signs them on our behalf.  Unfortunately the normal process doesn't apply for Microsoft-released stuff.
