### ISSUE TITLE
Distinguishing between file and project templates

### ISSUE THREAD

**Issue by daviwil** [PowerShell/Plaster#223]
In `plasterManifest.xml`, how should we distinguish between file and project templates?  Should we have conventional tags like "FileTemplate" and "ProjectTemplate" which must be there so that they can be listed in the appropriate UI in VS Code?  I'm going to have a separate command for scaffolding a file into the current workspace, seems like it's appropriate to think about that now since we added the PSScriptAnalyzer settings template.

Or maybe we should be a little more generic and call it "FolderTemplate" instead of "ProjectTemplate" since folks are also using this for things other than code projects?

**Comment by rkeithhill** [comment]
I had been following a Visual Studio convention of using "New" to create projects (slns) and "Add" to add things to existing projects.  But I'm definitely open to a different naming convention.

**Comment by daviwil** [comment]
That naming convention sounds great, but I'm looking for a metadata convention that can be used in code. Maybe the idea is that the Name (not the Title) can be used for that?

**Comment by rkeithhill** [comment]
Ah, yes then in that case the tags FileTemplate and ProjectTemplate seem like a reasonable way to go.  

Another option is to add that info to the schema as an optional (?) element or attribute:
```
<plasterManifest schemaVersion="0.3" xmlns="http://www.microsoft.com/schemas/PowerShell/Plaster/v1">
    <metadata>
        <type>file</type>
```
or maybe
```
<plasterManifest schemaVersion="0.3" xmlns="http://www.microsoft.com/schemas/PowerShell/Plaster/v1">
    <metadata>
        <name type="project">NewPowerShellScriptModule</name>
```

**Comment by daviwil** [comment]
Yeah, maybe the `<type>project</type>` is better since it stands out as an important part of the metadata.  We can make it optional and default it to `project`.

I think the last thing to decide is what the file/project terms should be.  Maybe instead of `file` vs `project` it should be `add` vs `create` or `new` like you were mentioning before.  I think a template could be used to add multiple files to an existing project so it doesn't really make sense to use `file` as the way to communicate an `add`.  Based on that, here are two more questions:

1. Does `create` communicate the intent that this template creates a new folder or project, or is there a better word?
2. Does `type` communicate the function of `add` and `create` or should it be something like `action` instead?  Maybe there's a better word?

I'd like to get this in for 1.1.0 because I'm already seeing an issue where the new Add PSScriptAnalyzer template is showing up in the "New Project" menu.  It'd be nice to have those paths clearly defined so that we can introduce an "Add Files to Project" command in the next big update.

**Comment by rkeithhill** [comment]
Maybe we take a page from the VS playbook: https://msdn.microsoft.com/en-us/library/tsyyf0yh.aspx and https://msdn.microsoft.com/en-us/library/ms247121.aspx

* ProjectTemplate
* ItemTemplate
* MultiFileItemTemplate

As for the element/attribute name `<type>`, I was originally thinking `<templateType>` but then I thought "template" was sort of implicit but maybe not.  `<templateType>` is less ambiguous.  

I can encoded those values into the schema for the element/attribute perhaps with a default value (if element is missing) of "Unspecified".  If I do encode the values it would be better if this were an attribute on `<plasterManifest>` e.g.:
```
<plasterManifest schemaVersion="1.0"
                 templateType="ProjectTemplate"
                 xmlns="http://www.microsoft.com/schemas/PowerShell/Plaster/v1">
```
I assume you will want this info added to the PassThru object?  

I should be able to implement this later today - say around 5 pm your time.

**Comment by daviwil** [comment]
Seems like Visual Studio's values are "Item" and "Project" without the "Template" part at the end, maybe we can just go with that.  I guess so long as the assumption is that "Item" can either be a single or multi-file template, this nomenclature should work alright.

Yep, definitely want it showing up in the PassThru object.

**Comment by daviwil** [comment]
I just remembered one other thing: for the "Item" template case, we need a way to specify which file to open once the item has been created.  For single-item templates that's pretty easy, I can just open the sole file that is created.  For multi-item templates, we might need some convention that says "the first created file is always opened".  Though I think this convention breaks down if you factor in that a file which exists might just get updated instead so it'd end up in the list of updated files.

How do we want to communicate the file/path to be opened in an editor on template completion?

**Comment by rkeithhill** [comment]
OK `Item` and `Project` is good.  You don't think we need a `MultiFileItem`?  Turns out the PSScriptAnalyzer settings template is multifile if you select VSCode as the editor (that also adds the .vscode\settings.json file).  

> How do we want to communicate the file/path to be opened in an editor on template completion?

Ooh, excellent idea!  In fact, can this open more than one file?  I could see cases where you would want to open a couple of files.  Now where to put this into the manifest.  It feels like it should go in the content area.  Perhaps a new attribute on `<file>`, `<newModuleManifest>`, `<modify>` and `<templateFile>`.  How about:
```xml
    <file condition="$PLASTER_PARAM_Editor -contains 'VSCode'"
          source="test\Module.Tests.ps1"
          destination="test\${PLASTER_PARAM_ModuleName}.Tests.ps1"
          openInEditor="true"/>
```
This attribute would not be required (no breaking existing manifests). Although I guess I need to bump the manifest scheme version to 1.1.  And yeah, this would get added to the PassThru object.

**Comment by daviwil** [comment]
Would `MultiFileItem` have different behavior than `Item`?  It certainly makes the intent clearer but I don't know that it would improve the functional design at all.  I can certainly be persuaded to have it if there's a clear benefit, though.

Nice, yeah, the `openInEditor` param seems like a good way to do it.  It'll require a little magic to make that work for new project windows, might have to do some cross-window communication request the list of files to be opened.  However, it'd be really sweet if we could have the new window open up the created project's README file.

Definitely seems like we'll need schema 1.1 with the templateType and openInEditor additions.

**Comment by rkeithhill** [comment]
> Would MultiFileItem have different behavior than Item? 

Um, I guess not.  OK, Project and Item it is for now.

**Comment by rkeithhill** [comment]
BTW should we make -TemplateType a required parameter on New-PlasterManifest?  Seems like we should otherwise folks won't use it.  And/or I could make it a required attribute.  But if I do that then we need a side-by-side schema (1.0 and 1.1) to validate against.  Doable but maybe we take a Mulligan on 1.0 and just add this to 1.0 since it's only been out less than a week?

Let's think about that for now, I'm going to commit this with 1.1 (templateType not required - no changes to New-PlasterManifest) and you can use it to test the corresponding updates to the extension.
```
TemplatePath    : C:\Users\Keith\GitHub\PowerShell\Plaster\src\Templates\NewPowerShellScriptModule
DestinationPath : C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out
Success         : True
TemplateType    : Project
CreatedFiles    : {C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out\FooUtils.psd1, 
                  C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out\FooUtils.psm1, 
                  C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out\test\FooUtils.Tests.ps1, 
                  C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out\.vscode\settings.json...}
UpdatedFiles    : {}
MissingModules  : {}
OpenFiles       : {C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out\FooUtils.psd1, 
                  C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out\FooUtils.psm1}
```
and
```
TemplatePath    : C:\Users\Keith\GitHub\PowerShell\Plaster\src\Templates\AddPSScriptAnalyzerSettings
DestinationPath : C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out
Success         : True
TemplateType    : Item
CreatedFiles    : {C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out\PSScriptAnalyzerSettings.psd1, 
                  C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out\.vscode\settings.json}
UpdatedFiles    : {}
MissingModules  : {}
OpenFiles       : {C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out\PSScriptAnalyzerSettings.psd1}
```

**Comment by daviwil** [comment]
I think making `-TemplateType` mandatory for `New-PlasterManifest` makes sense since we want people to use it going forward.  I don't think it needs to be mandatory in the 1.1 schema.  If it's not specified then it just won't show up in the editor's list of project or item templates.  Will still be usable in `Invoke-Plaster` though.  That seems pretty nicely backwards-compatible.

**Comment by rkeithhill** [comment]
OK PR is pending.  Check on mandatory parameter.  I think that makes sense.  What help text should we use for Project vs Item?   `Project` typically populates an empty folder/workspace and `Item` typically adds an item (file or a few files) to an existing folder/workspace?

**Comment by daviwil** [comment]
Yep, that sounds like the right direction.  Thanks a lot for sending the PR!  I'll finish up the doc additions and the rest, I need to add a `-TemplateType` param to `Get-PlasterTemplate` anyway :)
