### ISSUE TITLE
Plaster and Powershell 6 Installation Problem

### ISSUE THREAD

**Issue by lboening** [PowerShell/Plaster#228]
![powershell6](https://cloud.githubusercontent.com/assets/445481/21873687/fc6db530-d835-11e6-9936-eabc36e036be.png)

I couldn't install Plaster on my Mac. Will it install? Am I missing something?

I

**Comment by rkeithhill** [comment]
There have been a number of bugs fixed in the PowerShellGet area of PowerShell Core.  Can you update to [6.0.0-alpha.14](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.14)?

**Comment by lboening** [comment]
I updated to alpha.14, tried it again. Hey, it works now! Plaster install was success. Thanks.
