### ISSUE TITLE
How can retrieve $LatestSupportedSchemaVersion information ?

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#232]
Today $LatestSupportedSchemaVersion is a private variable.
I must read the code to known this information.
Or is it not relevant to make it public ?

**Comment by rkeithhill** [comment]
Use of this variable outside the module context isn't something I gave a lot of thought.  The module needs it (perhaps an older version) to know whether it can handle a particular manifest.  Test-ModuleManifest will tell you whether the version of Plaster you have will work with the specified module manifest.  

Do you have a good use case for directly exposing this variable?

**Comment by LaurentDardenne** [comment]
_"Do you have a good use case for directly exposing this variable?"_
No, beyond than filter the result of Get-PlasterTemplate.
