### ISSUE TITLE
Read-Host : name cannot be null or empty.

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#236]
With this statement :
```xml
 <parameter name='Directory' type='text' prompt='$env:APDATA'/>
```
when the $env:APDATA variable do not exist Plaster throw this exception :  
```Powershell
invoke-plaster -TemplatePath G:\PS\Plaster\TestProject  -DestinationPath C:\Temp\TestManifest -verbose
#...
#                                            v1.0.1
# ==================================================
# Read-Host : name cannot be null or empty.
# At C:\Program Files\WindowsPowerShell\Modules\Plaster\1.0.1\InvokePlaster.ps1:499 char:26
# +                 $value = Read-Host -Prompt $prompt
# +                          ~~~~~~~~~~~~~~~~~~~~~~~~~
#     + CategoryInfo          : InvalidArgument: (:) [Read-Host], PSArgumentException
#     + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.ReadHostCommand    
```
In this case I dont known where is the problem in the manifest.

plaster v 1.0.1
PS v 5.1

**Comment by LaurentDardenne** [comment]
With this statement :
```xml
 <parameter name='Directory' type='text' prompt=''/>
```
I get a warning :

> WARNING: Failed to create dynamic parameters from the template's manifest file. 
> Template-based dynamic parameters will  not be available until the error is corrected.  
> The error was: 
> Exception setting "HelpMessage": "Cannot process argument because the value of argument "value" is not valid. Change the value of the "value" argument and run the operation again."

But I dont known the name of the parameter

**Comment by rkeithhill** [comment]
Thanks for reporting this.
