### ISSUE TITLE
[PowerShell Gallery] Add manifest tag 'PSEditon_Desktop' 

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#239]
Have you plan to add tag  ['PSEdition_Desktop'](https://msdn.microsoft.com/en-us/powershell/gallery/psget/script/scriptwithpseditionsupport) into the Plaster manifest ?
Is Plaster supported on PowerShell Core editions ?

**Comment by rkeithhill** [comment]
Plaster should run on PS Core but I haven't tested on the latest PowerShell drop. What you won't get is full XSD validation.  That feature doesn't exist in .NET Core 1.x but is coming in 2.0.  

RE `PSEdition_Desktop` I'm not sure the manifest schema needs to change but we do need to provide access to $PSVersionTable and the $Is* variables in the constrained runspace. That way you can have conditional directives based on the platform Plaster is running on.
