### ISSUE TITLE
Missing CBH

### ISSUE THREAD

**Issue by zloeber** [PowerShell/Plaster#256]
I've been digging into the code and unless I'm missing something here where is any of the CBH that would have been used to generate the docs?

**Comment by rkeithhill** [comment]
The project uses platyPS i.e. mardown files in https://github.com/PowerShell/Plaster/tree/master/docs/en-US.  You can put CBH on your functions and then run a platyPS command to create the initial markdown files.  After that you can remove the CBH from the functions.  You use `New-MarkdownHelp` to generate the initial md file IIRC.

**Comment by zloeber** [comment]
Why would you want to remove the CBH? Wouldn't you want to recreate the documentation (via PlatyPS) at each build to account for any changes?
