### ISSUE TITLE
Invoke-Plaster Fails

### ISSUE THREAD

**Issue by stefanstranger** [PowerShell/Plaster#26]
When running Invoke-Plaster I get the following error:
    Create FooUtils.psd1
Microsoft.PowerShell.Management\Get-ChildItem : Cannot find path 'C:\Users\Stefan\RecurseTest'
because it does not exist.
At C:\users\Stefan\Documents\GitHub\Plaster\InvokePlaster.ps1:473 char:22
+ ...     $files = Microsoft.PowerShell.Management\Get-ChildItem @gciParams
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Stefan\RecurseTest:String) [Get-ChildItem]
   , ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

![plastertest](https://cloud.githubusercontent.com/assets/2125385/16170242/79bd12de-354c-11e6-979e-87f2381c5021.gif)

**Comment by rkeithhill** [comment]
Looks like a bug in the recursive filespec code I added a few weeks ago.  Thanks for finding this. I'll try to get this fixed shortly.

**Comment by rkeithhill** [comment]
I can't repro following along with the animated gif.  Did you tweak the plasterManifest.xml file in that examples dir?  If so, could you post that file here?  The `Recurse` directory should be going under `C:\Users\Stefan\Documents\GitHub\FooUtils` and not directly under your home dir.

**Comment by gerane** [comment]
This was fixed by #28
