### ISSUE TITLE
Error when the parameter name conatins -

### ISSUE THREAD

**Issue by LawrenceHwang** [PowerShell/Plaster#260]
Seeing following error while invoke-plaster:
```
VERBOSE: Performing the operation "Expand template file" on target "temp file for 'ReadMe.md'".
Invoke-Plaster : Exception calling "Replace" with "4" argument(s): "PowerShell expression failed execution. Location:
templateFile 'src\ReadMe.md.txt'. Error: The expression '$PLASTER_PARAM_repo-name' is invalid or threw an exception.
Error: Exception calling "Invoke" with "0" argument(s): "At line:1 char:20
+ $PLASTER_PARAM_repo-name
+                    ~~~~~
Unexpected token '-name' in expression or statement.""
At line:1 char:1
+ Invoke-Plaster -TemplatePath .\z_PipelineTemplate\ -DestinationPath t ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Plaster], MethodInvocationException
    + FullyQualifiedErrorId : RuntimeException,Invoke-Plaster
```

Looks like caused by the parameter name has `-`.
It works fine without `-`.

Eg: what's in the plasterManifest.xml,
```
  <parameters>
    <parameter name = 'Pipeline_repo-name'  type = 'text'  prompt = 'the name the repo'></parameter>
  </parameters>
```

Thanks!

**Comment by rkeithhill** [comment]
The value of the parameter name must be a valid PowerShell parameter name.  Not sure that this worth changing.  We could look at making the schema limit the characters allowed in the name attribute's value.  Then you would get an error that the manifest is not valid and it should point out that the name attribute has a value that violates the schema.

**Comment by LawrenceHwang** [comment]
Ah that makes sense. Thanks a bunch for the quick update.

Would be great to get the error during the schema validation.  👍
