### ISSUE TITLE
Recurse does not work if Invoking Plaster from outside of Template Directory

### ISSUE THREAD

**Issue by gerane** [PowerShell/Plaster#27]
When invoking Plaster from a directory outside of the template directory, it is resolving the relative path against the working directory.

Instead of:
```powershell
$PSCmdlet.GetUnresolvedProviderPathFromPSPath('C:\path\to\template\foldertorecurse)
```

It is resolving
```powershell
$PSCmdlet.GetUnresolvedProviderPathFromPSPath('foldertorecurse)
```

Which resolves to the current working directory + the folder to recurse.

**Comment by gerane** [comment]
I have a fix for this, which branch would you want me to PR against?

**Comment by rkeithhill** [comment]
There is only master at this point.  PR looks good.  There is one behavior of `Join-Path` I don't like which is:
```powershell
55> join-path c:\temp c:\foo
c:\temp\c:\foo
```
But I use it in quite a few places myself.  I need to check that the paths coming from the template are relative paths and throw if they are not.  That will have to wait a bit though as I'm currently integrating schematized XML into the project.

**Comment by rkeithhill** [comment]
BTW thanks for tracking down and fixing this!!
