### ISSUE TITLE
conditional plaster parameters

### ISSUE THREAD

**Issue by chreestopher** [PowerShell/Plaster#275]
It would be great to have an elegant way to have conditional plaster parameters
Something like below:

    <parameter name="AlternateParameterIncluded" type="text" prompt="Include Alternate Parameter?" />
    <parameter name="AltParamToInclude" type="text" prompt="Enter the optional alt parameter" condition="$PLASTER_PARAM_.AlternateParameterIncluded -ne $null" />

This would enable you to prompt for different parameters based on the previously entered parameters.

**Comment by rkeithhill** [comment]
This was added with PR https://github.com/PowerShell/Plaster/pull/255

**Comment by chreestopher** [comment]
Awesome, sorry i didnt look over th PRs before posting.

On Jul 14, 2017 2:53 PM, "Keith Hill" <notifications@github.com> wrote:

Closed #275 <https://github.com/PowerShell/Plaster/issues/275>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PowerShell/Plaster/issues/275#event-1164781914>, or mute
the thread
