### ISSUE TITLE
Example template "New PowerShell Manifest Module" uses incorrect powershell.exe path

### ISSUE THREAD

**Issue by kbakk** [PowerShell/Plaster#277]
- Plaster Version: 1.0.1 (installed from powershellgallery.com)
- OS: Windows 10, Version 1607

When running Invoke-Plaster with template path pointing to the example template "New PowerShell Manifest Module" version 1.0.0, the generated .vscode/tasks.json contains incorrect powershell.exe path (on my system):

Line 16:

    "command": "${env.windir}\\sysnative\\windowspowershell\\v1.0\\PowerShell.exe"

This results in an error in the output console: The system cannot find the path specified.

Changing the line to 

    "command": "${env:windir}\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"

or just

    "command": "powershell"

Successfully runs the tests. 

It could be I and the authors have different paths to powershell.exe (noticing others online also refers to this file path) - but shouldn't it always be in the system path, thus it should be possible to use the filename only, not the entire path?

**Comment by rkeithhill** [comment]
Thanks for the bug report. Fortunately, this has already been [fixed](https://github.com/PowerShell/Plaster/blob/master/src/Templates/NewPowerShellScriptModule/editor/VSCode/tasks.json#L16).  Hopefully we'll have an updated release out by early August.
