### ISSUE TITLE
Plaster corrupts binaries 

### ISSUE THREAD

**Issue by gerane** [PowerShell/Plaster#29]
There are multiple parts to this issue.

If Plaster processes a file like an exe, it will corrupt it even if it doesn't modify anything.

```powershell
function ProcessTemplate([string]$Path, $encoding) {
            if ($PSCmdlet.ShouldProcess($Path, $LocalizedData.ShouldProcessTemplateFile)) {
                $content = Get-Content $Path -Raw
                $pattern = '(<%=)(.*?)(%>)'
                $newContent = [regex]::Replace($content, $pattern, {
                    param($match)
                    $expr = $match.groups[2].value
                    Write-Verbose "Replacing template expr $expr in '$Path'"
                    ExpandString $expr
                },  @('IgnoreCase', 'SingleLine', 'MultiLine'))

                if ($Content -ne $newContent)
                {
                    Set-Content -Path $Path -Value $newContent -Encoding $encoding
                }
            }
        }
```

Every file Plaster processes it uses Set-Content with `$Encoding` even if there were no changes made to the file. Something like an exe might not have had a `utf8` encoding so this will corrupt the exe.

Where this becomes problematic is when using Recurse on a directory. If you have files in those directories, one might add `template = 'true'` so the template files in that directory are processed.

A fix that so far seems to work for me is to add a simple check

```powershell
                if ($Content -ne $newContent)
                {
                    Set-Content -Path $Path -Value $newContent -Encoding $encoding
                }
```

Instead of setting the content every single time, which creates unneeded room for error, I just added a check to see if $Content was actually altered via the Regex replace. 

However, now that there is Recurse type functionality, is this fix enough? Here are a few things to consider when dealing with Recurse.

* Should Plaster have a filetype ignore list?
* Should Plaster attempt to determine the File's current encoding and Set-Content using that encoding?
* Should we add a new property to the File Node that lets us specify certain files inside of a Recursed folder for Template.

I am pretty sure you could do the recurse without `template = 'true'` and then add other File Nodes with `template = 'true'` for files inside of the Recursed folder that need to be edited. The issue here is we will likely have users who do not know to do it this way and might use `template = 'true'` in the folder Recurse.

I am thinking I may go ahead and push the patch for the Set-Content, but wanted to discuss what I mentioned above as well.

**Comment by rkeithhill** [comment]
Yeah, we really don't want to attempt to template process binary files.  :-)  An ignore list (blacklist) or filter spec is one way to go.  Another is a whitelist.  Another one would be to split out the template processing into its own directive - separate from file copy.

**Comment by rkeithhill** [comment]
I'm going to go with a separate directive `<template>` that is similar to `<file>` except that it will implicitly treat the associated files as template files i.e. the `template` attribute will not be required (and will be removed from `<file>`).
