### ISSUE TITLE
What is the effort?

### ISSUE THREAD

**Issue by dfinke** [PowerShell/Plaster#32]
I've been going through PowerShell, psake etc creating Build, Test and Deploy steps. This can include ARM templates and inserting JSON snippets into the overall provisioning steps. I know 80% can be done with convention over configuration. I'm wondering what the effort would be to leverage Plaster to do this?

**Comment by rkeithhill** [comment]
Have a look at the [Examples\NewModuleTemplate\plasterManifest.xml](https://github.com/PowerShell/Plaster/blob/master/Examples/NewModuleTemplate/plasterManifest.xml).  It should give you an idea of what is possible.  Also look at the build.ps1 file that gets scaffolded if you select the PSake option.

**Comment by rkeithhill** [comment]
@dfinke I'm closing this issue but if you disagree let me know and I'll re-open it.
