### ISSUE TITLE
Invoke-plaster returns an object without the -passthru argument.

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#326]
See [this line](https://github.com/PowerShell/Plaster/blob/master/src/InvokePlaster.ps1#L1414).

**Comment by rkeithhill** [comment]
Thanks.  Should be using Write-Host on that info.

**Comment by LaurentDardenne** [comment]
Probably, but the [documentation](https://github.com/PowerShell/Plaster/blob/master/docs/en-US/Invoke-Plaster.md#-passthru) is to be reviewed it seems to me.

If the original idea was to propagate this information, you might as well complete(update ?) the [custom object](https://github.com/PowerShell/Plaster/blob/master/src/InvokePlaster.ps1#L198).

By the way, the people I'm working with right now find this tool very good.
Yes, he is. :-)
