### ISSUE TITLE
Plaster build script tasks for signing files

### ISSUE THREAD

**Issue by davegreen** [PowerShell/Plaster#33]
Hello,

I've been using some of the ideas from the Build.ps1 script in my psake build script and I added a few tasks to enable script signing that I use on some other projects.

I can create a PR to add/merge some of the work that I've done on the [build script](https://github.com/davegreen/PowerShell/blob/master/Modules/Timezone/Build.PSake.ps1) i use. It could probably use a bit of work but I wanted to know whether this was something that you thought plaster could provide functionality for.

Thanks,
Dave Green

**Comment by rkeithhill** [comment]
The current build.ps1 psake script is by no means done.  I'd like to add a docs build task that perhaps uses platyPS.  

So yeah, have a task to do script signing (perhaps based on existence of a CertificatePath/Name property) task would be nice to have.  Go ahead and submit a PR and we can work from there on how best to integrate it in.

**Comment by davegreen** [comment]
Thank you for the feedback and help with this! It's been fun to contribute 😄
