### ISSUE TITLE
Completely suppress output of invoke-plaster

### ISSUE THREAD

**Issue by TechnicallyJoe** [PowerShell/Plaster#349]
Hi

I'm writing some Pester tests that will tests various things in a plaster invoke. Like ensuring the files described in the templatefile haven't been moved/deleted. However the Output of the invoke-plaster is cluttering the screen when i run the tests.

I can't seem to figure out any way to surpress output completely. Is this possible?

I've tried passing to various variations of Out-Null, $Null = invoke-plaster etc but nothing has worked so far. -NoLogo is the only thing that has helped in this regard, but not enough.

**Comment by tommymaynard** [comment]
Maybe try  Invoke-Plaster’s PassThru parameter to create an InvokePlasterInfo object. Once you have an object, you can export it away, or perhaps pipe to Out-Null. I’m not in a position to try myself, but maybe this will help. I did something like this with Pester: https://tommymaynard.com/comfortably-save-a-pester-test-2017/

**Comment by rkeithhill** [comment]
Also, depending on the version of PowerShell you are on, you can redirect the info (host) stream to null e.g. `6> $null`.

**Comment by TechnicallyJoe** [comment]
Okay, some info:
Versions:
PowerShell: 5.1.16299.820
Pester: 4.4.2
Plaster: 1.1.3

What I've tried so far:

``` PowerShell
$null = Invoke-Plaster @params
$null = Invoke-Plaster @params -PassThru
Invoke-Plaster @params -PassThru | Out-Null
[System.Void](Invoke-Plaster @params)
[System.Void](Invoke-Plaster @params -PassThru)
[System.Void]($null = Invoke-Plaster @params -PassThru -OutVariable null)
```
Nothing has worked so far

**Comment by rkeithhill** [comment]
Did you try:
```
Invoke-Plaster @params 6>$null
```
If that doesn't work, try:
```
Invoke-Plaster @params *>$null
```

**Comment by TechnicallyJoe** [comment]
> 
> 
> Did you try:
> 
> ```
> Invoke-Plaster @params 6>$null
> ```
> 
> If that doesn't work, try:
> 
> ```
> Invoke-Plaster @params *>$null
> ```

Well that was quite impressive.
`Invoke-Plaster @params 6>$null` Worked like a charm!

Completely supressed the output. If you don't mind, could you explain the 6>$null?

**Comment by rkeithhill** [comment]
PowerShell has more than just the typical shell's streams. It has 1 (stdout) and 2 (stderr) but also 3 (warning), 4 (verbose), 5 (debug) and 6 (information/host).  You can redirect any one of these or all (with *) to a file or to $null.  See `man about_redirection` for more details.

**Comment by TechnicallyJoe** [comment]
TIL :) - Thanks!
