### ISSUE TITLE
The module localization is not supported

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#38]
The localization is not yet supported :
```powershell
cd 'C:\Users\Laurent\Downloads\Plaster-master\Examples\NewModuleTemplate'
Import-Module ..\..\Plaster.psd1
# Import-LocalizedData : Cannot find the Windows PowerShell data file 'PlasterResources.psd1' in directory
# 'C:\Users\Laurent\Downloads\Plaster-master\fr-FR\', or in any parent culture directories.
# At C:\Users\Laurent\Downloads\Plaster-master\Plaster.psm1:32 char:1
# + Import-LocalizedData LocalizedData -FileName PlasterResources
# + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     + CategoryInfo          : ObjectNotFound: (C:\Users\Lauren...rResources.psd1:String) [Import-LocalizedData], PSInv
#    alidOperationException
#     + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData

Get-Culture
# LCID             Name             DisplayName
# ----             ----             -----------
# 1036             fr-FR            Français (France)
$PSVersionTable
# Name                           Value
# ----                           -----
# PSVersion                      5.0.10586.117
# PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0.10586.117}
# BuildVersion                   10.0.10586.117
# CLRVersion                     4.0.30319.42000
# WSManStackVersion              3.0
# PSRemotingProtocolVersion      2.3
# SerializationVersion           1.1.0.1
```

**Comment by rkeithhill** [comment]
Thanks for finding and submitting this issue.  Guess I'll need to figure out how PowerShell handles fallback to a default culture.  And then maybe "someone" could localize the strings to French (but only after development gets closer to the 1.0 release).  :-)

**Comment by LaurentDardenne** [comment]
>>Guess I'll need to figure out how PowerShell handles fallback to a default culture. 
Copy the help files into the module directory.

>>And then maybe "someone" could localize the strings to French.
I could do it.

**Comment by rkeithhill** [comment]
> Copy the help files into the module directory.

Thanks.  That's simple enough.

**Comment by rkeithhill** [comment]
@LaurentDardenne BTW can you try man Invoke-Plaster to see if that works or do we need a copy of the help file as well in the module directory?

**Comment by LaurentDardenne** [comment]
With a new 'installation', the command line "man Invoke-Plaster" works, but not the Import-Module Cmdlet.

**Comment by rkeithhill** [comment]
OK I'm doing exactly what the new Compress/Expand-Archive commands are doing.  I'm not sure why it would work for these two commands and not Plaster - unless something happens at build time I haven't seen.   I assume you get localized messages from these two commands, right?

Have a look - https://github.com/PowerShell/Microsoft.PowerShell.Archive/blob/master/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.psm1

**Comment by LaurentDardenne** [comment]
Same error with _Microsoft.PowerShell.Archive.psm1_
Try it :

- Rename 'en-US\PlasterResources.psd1' to 'en-US\Plaster.psd1'
- In Plaster.psm1 comment/remove **_Data_** section and  use only _BindingVariable_ parameter : Import-LocalizedData LocalizedData

**Comment by rkeithhill** [comment]
Ha!  Serves me right for "assuming" that approach was the correct approach.  Obviously, I need to read up on script i18n.  Thanks for trying the archive commands.

**Comment by LaurentDardenne** [comment]
See
https://rkeithhill.wordpress.com/2009/10/21/windows-powershell-2-0-string-localization/
I have moved  the file 'en-US\Plaster.Resources.psd1'  into the module root, it works.

**Comment by rkeithhill** [comment]
I think what we've got now works and seems to be what Microsoft is doing in a number of modules installed with PowerShell: Archive, AssignedAccess, SmbShare and PSDesiredStateConfiguration.
