### ISSUE TITLE
Enable support for localized templates

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#43]
Today it is impossible to use a hashtable into a template :
```powershell
Import-LocalizedData -BindingVariable PLASTER_MyTemplate -Filename MyTemplate.psd1
Invoke-Plaster ...

  #Xml template
<message>$($PLASTER_MyTemplate.VcsTask)</message>
<message>$($PLASTER_MyTemplate.$PLASTER_PARAM_License)</message>


 #Module.T.ps1
$ModuleManifestName = '<%=$PLASTER_PARAM_ModuleName%>.psd1'
# <%=${PLASTER_GUID1}%> - testing use of PLASTER predefined variables.
# <%=$PLASTER_MyTemplate.ManifestComment%> -
```
Adding this feature would be appreciated.

**Comment by rkeithhill** [comment]
Localization support, eh?  Good catch. Let me think about this one.  Seems like you shouldn't have to do the Import-LocalizedData outside of Invoke-Plaster.  Would be better if Invoke-Plaster did this for you if you somehow declared you were using localized strings.  Not sure if this will make the initial release though.

**Comment by LaurentDardenne** [comment]
_Localization support, eh? Good catch. Let me think about this one._
Yes, I don't know if it's a good idea or a bad good idea :-) 

How to manage a 'file' element for 2 cultures (fr-FR,en-US) when they comes from a parameter of 'multichoice' type ?
```powershell
<file source='ApacheLicense.txt'
      destination='LICENSE.txt'
      template='true'
      condition="$PLASTER_PARAM_License -eq 'Apache'"/>
```
Do I duplicate the 'file' elements ?
```powershell
<file source='\fr-FR\ApacheLicense.txt'
      destination='\fr-FR\LICENSE.txt'
      template='true'
      condition="$PLASTER_PARAM_License -eq 'Apache' -and $PLASTER_PARAM_CultureOptions -contains "fr-FR"/>

<file source='\en-US\ApacheLicense.txt'
      destination='\en-US\LICENSE.txt'
      template='true'
      condition="$PLASTER_PARAM_License -eq 'Apache' -and $PLASTER_PARAM_CultureOptions -contains "en-US"/>
```
Do I duplicate the xml template  or do  i use later a PSake task ?
Currently a hashtable can help me.

**Comment by rkeithhill** [comment]
I'm wondering if we need something like a sub-element of `<content>` such as `<content><localized culture='fr-FR'>`.  Then Plaster could automatically do the stuff under that element when $PSUICulture is fr-FR.  Thoughts?

**Comment by LaurentDardenne** [comment]
_Then Plaster could automatically do the stuff under that element when $PSUICulture is fr-FR._
This principle seems to me appropriate.

But there is also this elements :
```xml
    <metadata>
        <title>New Module Project</title>
        <!-- For display by UI's in hover help -->
        <description>Plaster template for creating the files for a PowerShell module.</description>
     ...
```xml

**Comment by rkeithhill** [comment]
What do you think about these [NuGet approaches to localization](https://docs.nuget.org/create/creating-localized-packages)?  The manifest file is largely inspired by the NuGet nuspec file.  I kind of like the second (satellite pkg) approach but it does have a few icky downsides.  How we wind up distributing these templates (most likely as a PowerShell module via PSGallery) will impact how we localize as well.

**Comment by LaurentDardenne** [comment]
_What do you think about these NuGet approaches to localization?_ 
This seems to me an interesting solution.
This makes the manifest more readable.

**Comment by LaurentDardenne** [comment]
Thanks Keith.

_Apologies in advance for the French translation._ 
My English is worse :-)

For me, this implementation requires the use of a build process  (New LocalizedManifestPlaster) outside Plaster.

**Comment by LaurentDardenne** [comment]
I get a wrong display :
_"Votre nouveau projet de module de PowerShell FooUtils avec le contrÃ´le de version Git a Ã©tÃ© crÃ©Ã©.
Vous pouvez gÃ©nÃ©rer votre projet en exÃ©cutant la tÃ¢che de Â«Â chantierÂ Â» en appuyant sur Ctrl + P, puis tapez 'tas
k build'._"
                                               
When I use the UTF8 encoding for the plasterManifest_fr-FR.xml file, the display is correct
_"Votre nouveau projet de module de PowerShell FooUtils avec le contrôle de version Git a été créé.
Vous pouvez générer votre projet en exécutant la tâche de « chantier » en appuyant sur Ctrl + P, puis tapez 'task build'."_

**Comment by rkeithhill** [comment]
Hmm, VSCode shows me that the plasterManifest_fr-FR.xml is UTF-8.  Did you save it as UTF-8 with BOM?

**Comment by rkeithhill** [comment]
> For me, this implementation requires the use of a build process (New LocalizedManifestPlaster) outside Plaster.

Can you elaborate? Is this a problem or just an observation?

**Comment by LaurentDardenne** [comment]
_Did you save it as UTF-8 with BOM?_
Yes, the latest commit fix this problem.

_Can you elaborate? Is this a problem or just an observation?_
Just an observation. Imho, maintain two files is a possible source of error.

_Is this a problem_
No, it requires more work.

I have created a [test repository](https://github.com/LaurentDardenne/TestProject)
I  will add a comment about my extra code.

**Comment by LaurentDardenne** [comment]
[Here's](https://github.com/LaurentDardenne/TestProject/blob/master/NewLocalizedManifest.ps1) what I need to do to create each localized file.
