### ISSUE TITLE
Detect parameter defaults where possible

### ISSUE THREAD

**Issue by MartinSGill** [PowerShell/Plaster#46]
It would be a nice convenience feature, e.g. if no previous value is stored (#9) to try and guess a good default value.

for example for an Author/Name field:

```
git config user.name
```

or worst case:

```
$env:USERNAME
```

The same for email etc.

This may require custom parameter types (i.e. author-name, instead of string), so that it's available to use in template choices.

**Comment by rkeithhill** [comment]
Considering that the user's entry can be "stored" as the new default value after the first invocation of the template, do you think this is necessary?  That is, it would only apply the first time you invoked the template.

**Comment by MartinSGill** [comment]
Necessary no; nice to have, sure.

I was using yeoman on a new machine the other day and it pre-populated my author name. I actually puzzled over it for a while as to where it could come from and decided in the end it came from my git config.

I thought it was a nice touch; one of those little things that impresses you when using something new.

**Comment by rkeithhill** [comment]
Oh sure, taunt me with "well, yeoman can do it".  How did you find my buttons to push so quickly?  ;-)  

I guess it wouldn't be too hard to look for a user's global git config file and see if it's in there.  I'll see if I can get this in.

**Comment by rkeithhill** [comment]
Addressed by PR.
