### ISSUE TITLE
How to create empty directories ?

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#47]
Is the 'File' element can manage this case ?
```Powershell
Import-Module Plaster

cd G:\PS\Plaster
md FabrikamNewModule

$PlasterParams = @{
    TemplatePath = "$PWD\FabrikamNewModule"
    Destination = "$PWD\Out\FabrikamNewModule"
    ModuleName = 'MapPSCode'
    FullName = 'John Q. Doe'
    Version = '1'
    Options = 'PSake','Pester','Git',
    Editor = 'VSCode'
    License = 'MIT'               
}

$Directories=@(
  'Demos',
  'en-US',
  'fr-FR',
  'Help',
  'Tests',
  'Tools',
  'Bin',
  'FormatData',
  'Modules',
  'Setup',
  'TypeData'
)

md $PlasterParams.Destination
Push-Location $PlasterParams.Destination 
$Directories|
Foreach {
 md $_ -Verbose -ea SilentlyContinue > $null
} 
Pop-Location

#Invoke-Plaster @PlasterParams ...
```

**Comment by rkeithhill** [comment]
Yes, the `<file>` directive is meant to cover all file system operations such as copy file, create the subfolder if it does not exist.  

This issue of creating empty directories came up before and I thought I had fixed it but perhaps the changes for wildcard file spec broke it.  I'll look into it. 

BTW if you use Git, you do know that Git will not commit an empty directory, right?

**Comment by LaurentDardenne** [comment]
_BTW if you use Git, you do know that Git will not commit an empty directory, right?_
I use what my customers use :  Git, Subversion, ... :-)

**Comment by MartinSGill** [comment]
The solution git users tend to use is to create an empty file like  '.keep' in the folder. You could use the same approach.

**Comment by rkeithhill** [comment]
This is now supported with the latest PR.

**Comment by LaurentDardenne** [comment]
Thank you Keith.
