### ISSUE TITLE
Invoke-Plaster no longer works with the example

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#53]
Following the latest commit, Invoke-Plaster throw an exception :
```powershell
[STA] C:\Users\Laurent\Downloads\Plaster-master\Examples\NewModuleTemplate> Invoke-Plaster @PlasterParams -Force
Invoke-Plaster : A parameter cannot be found that matches parameter name 'FullName'.
```
in xml :
```xml
        <parameter name='FullName' type='author' store='encrypted' prompt='Enter your fullname'/>
```
in InvokePlaster.ps1 the code in dynamicparam do not manage the 'author' type.

**Comment by rkeithhill** [comment]
Yup.  I'll try to get a fix for that in tonight.  For now, change the type to input for FullName and Email to `input`.
