### ISSUE TITLE
Consider MIT License as default license

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PowerShell/Plaster#56]
Hi!

Not all organizations care about licenses, but some do.  For the sake of [folks like Justin](https://twitter.com/zippy1981/status/581612072577974274), it might be worth leaning towards a simple, permissive license like the MIT license as a default, rather than *None*.

I can see arguments in both directions, but if one is specified by default, it will make it harder for folks to just ignore it, or be scared off without realizing there's a [decent boiled down overview](http://choosealicense.com/).

Cheers!

**Comment by rkeithhill** [comment]
I definitely open to what the default "license" should be - if any.  I can see folks developing "internal only" modules not giving a rip about a license.  However, if someone is publishing to the PSGallery, they will need a license.

**Comment by rkeithhill** [comment]
After thinking about this some more, I'm a bit concerned about the legal ramifications of supplying a `default license` for those folks that just "click through" the wizard.  I don't think it is too onerous to have to select a license and you can always select `None` and add a license later if you want to research the different types of license.

**Comment by daviwil** [comment]
Yep, I agree, we shouldn't prescribe a license by default.
