### ISSUE TITLE
DynamicParams of inovke-Pester errors and shows verbose out

### ISSUE THREAD

**Issue by gaelcolas** [PowerShell/Plaster#6]
When you tab autocomplete the Invoke-Plaster, the DynamicParam is executed and because you haven't set the Path yet, it returns an error, which is then only partially displayed. (see yellow bit in output below)
![image](https://cloud.githubusercontent.com/assets/8962101/15389539/635b01fe-1daf-11e6-95db-8bafb5d3a499.png)

**Comment by rkeithhill** [comment]
Yeah that write-warning needs more info.  And it is debatable whether it should be written to the warning or verbose stream. Did we mention this is an early preview.  :-)
