### ISSUE TITLE
Question about Encoding attribute

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#60]
The xsd documentation says :
```xml
  <xs:simpleType name="EncodingType">
    <xs:annotation>
      <xs:documentation>
        The encoding to use for writing to a file.
      </xs:documentation>
    </xs:annotation>
```
What about for the encoding to use for _reading_ a file ?

**Comment by rkeithhill** [comment]
PowerShell/.NET typically does a good job of detecting the encoding of text files before it converts them to Unicode strings for processing inside PowerShell.  However, when writing those Unicode strings out to a file, the user should be able to specify if they want another encoding - typically UTF8 or UTF8-NoBOM.

**Comment by LaurentDardenne** [comment]
Ok, but this implies a upstream control :
```Powershell
$t=@(
 "Default",
 "Ascii",
 "BigEndianUnicode",
 "BigEndianUTF32",
 "Oem",
 "Unicode",
 "UTF32",
 "UTF7",
 "UTF8"
)

$t|% {
     Write-Warning "Encoding :  $PSItem"
  @'
  #encoding test 
  $i=10
  $échec=$true

  Write "test : à é ï ù Ô" 
  10 -eq $i
  $échec -eq $true
'@ |Set-content -path C:\Temp\TestEncoding.ps1 -encoding $PSItem
  gc "C:\Temp\TestEncoding.ps1"   
  &"C:\Temp\TestEncoding.ps1"
}
```
Is it possible to change the default encoding value for all files (create/copy/modify) ?

**Comment by rkeithhill** [comment]
Copy should not mess with encoding - the file may be a dll.  For template expansion and modify, the default is the PowerShell default for Set-Content which is ASCII IIRC.
