### ISSUE TITLE
The template functions could they be public ?

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#66]
The template functions could they be public (Invoke-Template) or they are intended to be private ?

**Comment by rkeithhill** [comment]
Which template functions are you referring to?  Are you talking about some of the private functions in Invoke-Plaster?

**Comment by rkeithhill** [comment]
At this point the plan is not to expose those functions as module commands.  The primary interface to this module is the plasterManifest.xml file and the Invoke-Plaster command.
