### ISSUE TITLE
How do you consider a tied variable inside the plaster context ? 

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#80]
In this [file](https://github.com/PowerShell/Plaster/blob/master/docs/DesignNotes.md), it is says :
"_In a future release, we may allow a template to execute arbitrary script but that will be inside a special directive perhaps called < script>._" 

How do you consider a tied variable inside the plaster context ? Is it safe or not ? 

```powershell
#Tied Variable
class GuidVariable : System.Management.Automation.PSVariable { 
  GuidVariable():base("Guid", 0, "ReadOnly,AllScope") {}
 
  [object] get_Value(){ return [System.Guid]::NewGuid() } 
} 
#create $Guid Variable
$ExecutionContext.SessionState.PSVariable.Set([GuidVariable]::new()) 

Invoke-Plaster...
```
into the xml template :
```xml
  <message>`n1 : $Guid </message>
  <message>`n2 : $Guid </message>
```
This use could it be forbidden ?

**Comment by rkeithhill** [comment]
Plaster allows you to access any variable available in PowerShell.  You can access $env variables, $home, etc.  

BTW why not use the built-in PLASTER variables $PLASTER_Guid1 thru $PLASTER_Guid5?  Their values are generated new on each invocation.

**Comment by LaurentDardenne** [comment]
_BTW why not use the built-in PLASTER variables $PLASTER_Guid1 thru $PLASTER_Guid5?_
Yes I know, it was a simple example code.
