### ISSUE TITLE
Erroneous display when a file is outside the Plaster destination path

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#81]
I try to create an xml file outside the path destination : 
```xml
    <templateFile source='Templates\ShelLibrary-ms.T.xml'
        destination='${Env:AppData}\Microsoft\Windows\Libraries\${PLASTER_PARAM_ProjectName}.library-ms'
        encoding='UTF8'/>  
```
I know this it not supported, but the file name displayed is not the used file name : 
![bug-filepath1](https://cloud.githubusercontent.com/assets/4894452/17362894/9628b4b0-5977-11e6-8200-46284b47825e.png)
With -verbose :
![bug-filepath2](https://cloud.githubusercontent.com/assets/4894452/17362900/a566fb26-5977-11e6-8d11-147769273f59.png)

For this operation i must create a post installation script.

**Comment by rkeithhill** [comment]
OK I have a fix for this I'm about to commit. Would appreciate it if you could take it for a spin to see if it meets your expectations.  Thanks.

**Comment by LaurentDardenne** [comment]
>>Would appreciate it if you could take it for a spin to see if it meets your expectations
Yes, absolutely.
Thanks :-)
