### ISSUE TITLE
Possible conflict whith the default value store file

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#87]
See the fix #43

_First step_:
I have only one manifest (default).
The default value store file do not exist.

plasterManifest.xml
```xml
...
 <parameter name='ModuleDesc' type='text' default='My module in English'  store='text' prompt='Enter a description of the module (required for publishing to the PowerShell Gallery)'/>
... 
```
I enter a value (ModuleDesc parameter).
The file into the store is single.

_Second step_:
I add a manifest for my culture .

plasterManifest_fr-FR.xml
```xml
...
 <parameter name='ModuleDesc' type='text' default='Mon module en Français' store='text' prompt='Saisissez une description du module (requis pour la publication sur PowerShell Gallery)'/> 
...
``` 
In this case the default is english (The file exist into the store). The default french message is not used.

**Comment by rkeithhill** [comment]
I'm not entirely sure what the right answer is here.  I believe it will be much more common to "store" values like user name and email address which won't likely change with the culture.  I'm inclined not to change this for v1.0.  Get more feedback and go from there.  Unless you think this is a showstopper on the localization front?

**Comment by LaurentDardenne** [comment]
_Unless you think this is a showstopper on the localization front?_
No idea, let's keep our fingers crossed :-)
