### ISSUE TITLE
Question about the versioning between a schema and a Module

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#89]
How to Plaster will manage the versioning ?

Does each schema version will be coupled with a module version ?
Or a module version will be able to manage multiple versions of a schema?

What will happen in the following case:
I have  the version 1.0 of the module and I download a manifest for the schema version 1.2 ?

**Comment by rkeithhill** [comment]
Thanks for the reminder to add the schemaVersion check code.  I will be checking that in soon. The basic idea is this.  The XSD namespace should rarely change i.e. only in cases of breaking changes.  In theory, Plaster could support v1, v2, v3 with different code paths to handle the different schema versions.  That is a lot of extra work so there will be motivation to avoid breaking changes.  In fact, the most likely breaking change WRT the manifest is if we decided to move to a different file format (JSON or PS DSL).

What I do expect to happen is that we incrementally add manifest directives over time.  This will necessitate an increment to the minor version number of the schemaVersion attribute e.g. `<plasterManifest schemaVersion="major.minor"/>`.

Each version of Plaster will have a module level variable:
```powershell
$LatestSupportedSchemaVersion = [System.Version]'0.3'
```
If someone attempts to load a Plaster template with a version number greater than this, they will get the following error message:
```
The template's manifest schema version (1.1) requires a newer version of Plaster. Update the Plaster module and try again.
```
