### ISSUE TITLE
get from .gitignore file name and email

### ISSUE THREAD

**Issue by McAndersDK** [PowerShell/Plaster#92]
265f2f8 break if the $env:home is on a network path. atleast if powershell are running in admin mode.
were need to be an test-path inplace before trying the join-path as it thro:
Join-Path : Cannot find drive. A drive with the name 'Z' does not exist.
At C:\GIT\Powershell-Imported\Plaster\src\InvokePlaster.ps1:1079 char:23
+     $gitConfigPath = (Join-Path $env:Home '.gitconfig')

**Comment by rkeithhill** [comment]
Thanks for reporting this!
