### ISSUE TITLE
How to document a manifest ?

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#93]
What naming convention must be used for the manifest help file ?

**Comment by rkeithhill** [comment]
Not sure what you're referring to here.  You're not talking about the localized manifest file, right?

**Comment by LaurentDardenne** [comment]
Sorry, I talked of a helpfile (PlasterManifest.xml + PlasterManifest.Help.txt)
A cmdlet can be documented, but what about for a Plaster manifest ?

**Comment by rkeithhill** [comment]
At this point, it is likely to be just XML comments in the manifest file with perhaps a readme or about_templatename.txt file in the appropriate dir (template root or under <culture-locale>) depending on exactly how we distribute Plaster templates.  The about topic would apply if we decide to distribute as a module via PSGallery. 

Also, the manifest's `<description>` tag is meant to be displayed in a UI as the, well, description of what the template does.  That is what I believe to be the most used form of documentation.  I would expect an editor like VSCode to expose that description to the end user.
