### ISSUE TITLE
Invoke-Plaster throw an ArgumentNullException with a zero-length file

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#97]
This balise requiert a file with a length greater than zero :
```xml
 <templateFile source='DirectoriesProject\**'  destination='' encoding='UTF8'/>
```
otherwise it raises an exception :
> VERBOSE: Performing the operation "Transformation du fichier de modèle" on target "fichier temporaire pour 'en-US\\.gitkeep'".
> Invoke-Plaster : Exception calling "Replace" with "4" argument(s): "La valeur ne peut pas être null.
> Nom du paramètre : input"

InvokePlaster.ps1 : 
```powershell
 $content = Get-Content -LiteralPath $srcPath -Raw
 $pattern = '(<%=)(.*?)(%>)'
 $newContent = [regex]::Replace($content, $pattern, {  ....

**Comment by rkeithhill** [comment]
Thanks for finding this.
